export type ThemeId = 'classic' | 'gamer' | 'space' | 'candy';

export type ThemeConfig = {
  name: string;
  emoji: string;
  vars: Record<string, string>;
  emojiColors: [string, string, string, string, string, string]; // 6 emoji bg colors
};

export const themes: Record<ThemeId, ThemeConfig> = {
  classic: {
    name: 'קלאסי',
    emoji: '🌟',
    vars: {
      '--zoomi-bg': '#ffffff',
      '--zoomi-text': '#4a5568',
      '--zoomi-shadow': '0 24px 48px rgba(219,39,119,0.1)',
      '--zoomi-radius': '36px',
      '--zoomi-btn-radius': '25px',
      '--zoomi-header-color': '#9ca3af',
      '--zoomi-hand-lowered-bg': '#f1f5f9',
      '--zoomi-hand-lowered-text': '#475569',
      '--zoomi-hand-lowered-hover': '#e2e8f0',
      '--zoomi-hand-raised-start': '#fbbf24',
      '--zoomi-hand-raised-end': '#f59e0b',
      '--zoomi-hand-raised-text': '#1a1a1a',
      '--zoomi-hand-raised-shadow': 'rgba(251,191,36,0.4)',
      '--zoomi-mute-unmuted': '#22c55e',
      '--zoomi-mute-unmuted-hover': '#16a34a',
      '--zoomi-mute-unmuted-shadow': 'rgba(34,197,94,0.3)',
      '--zoomi-mute-muted': '#ef4444',
      '--zoomi-mute-muted-hover': '#dc2626',
      '--zoomi-mute-muted-shadow': 'rgba(239,68,68,0.3)',
      '--zoomi-minimize-bg': '#edf2f7',
      '--zoomi-minimize-text': '#a0aec0',
      '--zoomi-focus-color': '#7c3aed',
    },
    emojiColors: ['#fee2e2', '#dcfce7', '#fef3c7', '#e0f2fe', '#f3e8ff', '#ffedd5'],
  },

  gamer: {
    name: 'גיימר',
    emoji: '🎮',
    vars: {
      '--zoomi-bg': '#1a1a2e',
      '--zoomi-text': '#e2e8f0',
      '--zoomi-shadow': '0 24px 48px rgba(57,255,20,0.15)',
      '--zoomi-radius': '12px',
      '--zoomi-btn-radius': '8px',
      '--zoomi-header-color': '#39ff14',
      '--zoomi-hand-lowered-bg': '#16213e',
      '--zoomi-hand-lowered-text': '#94a3b8',
      '--zoomi-hand-lowered-hover': '#1e2d4a',
      '--zoomi-hand-raised-start': '#39ff14',
      '--zoomi-hand-raised-end': '#00e676',
      '--zoomi-hand-raised-text': '#0a0a0a',
      '--zoomi-hand-raised-shadow': 'rgba(57,255,20,0.4)',
      '--zoomi-mute-unmuted': '#39ff14',
      '--zoomi-mute-unmuted-hover': '#32e612',
      '--zoomi-mute-unmuted-shadow': 'rgba(57,255,20,0.3)',
      '--zoomi-mute-muted': '#ff073a',
      '--zoomi-mute-muted-hover': '#e6002e',
      '--zoomi-mute-muted-shadow': 'rgba(255,7,58,0.3)',
      '--zoomi-minimize-bg': '#16213e',
      '--zoomi-minimize-text': '#39ff14',
      '--zoomi-focus-color': '#39ff14',
    },
    emojiColors: ['#2a1a3e', '#1a2e1a', '#2e2a1a', '#1a1a2e', '#2e1a2a', '#1a2e2a'],
  },

  space: {
    name: 'חלל',
    emoji: '🚀',
    vars: {
      '--zoomi-bg': '#1e1045',
      '--zoomi-text': '#e0d4ff',
      '--zoomi-shadow': '0 24px 48px rgba(99,102,241,0.2)',
      '--zoomi-radius': '28px',
      '--zoomi-btn-radius': '20px',
      '--zoomi-header-color': '#a78bfa',
      '--zoomi-hand-lowered-bg': '#2d1b69',
      '--zoomi-hand-lowered-text': '#c4b5fd',
      '--zoomi-hand-lowered-hover': '#3b2480',
      '--zoomi-hand-raised-start': '#818cf8',
      '--zoomi-hand-raised-end': '#6366f1',
      '--zoomi-hand-raised-text': '#ffffff',
      '--zoomi-hand-raised-shadow': 'rgba(129,140,248,0.4)',
      '--zoomi-mute-unmuted': '#6366f1',
      '--zoomi-mute-unmuted-hover': '#4f46e5',
      '--zoomi-mute-unmuted-shadow': 'rgba(99,102,241,0.3)',
      '--zoomi-mute-muted': '#ec4899',
      '--zoomi-mute-muted-hover': '#db2777',
      '--zoomi-mute-muted-shadow': 'rgba(236,72,153,0.3)',
      '--zoomi-minimize-bg': '#2d1b69',
      '--zoomi-minimize-text': '#a78bfa',
      '--zoomi-focus-color': '#818cf8',
    },
    emojiColors: ['#3b1d6e', '#1d3b6e', '#3b2d1d', '#1d3b3b', '#3b1d3b', '#2d3b1d'],
  },

  candy: {
    name: 'סוכריה',
    emoji: '🍬',
    vars: {
      '--zoomi-bg': '#fff0f6',
      '--zoomi-text': '#7c3a5e',
      '--zoomi-shadow': '0 24px 48px rgba(244,114,182,0.15)',
      '--zoomi-radius': '40px',
      '--zoomi-btn-radius': '30px',
      '--zoomi-header-color': '#f472b6',
      '--zoomi-hand-lowered-bg': '#fce4ec',
      '--zoomi-hand-lowered-text': '#9d4b73',
      '--zoomi-hand-lowered-hover': '#f8d0df',
      '--zoomi-hand-raised-start': '#fb923c',
      '--zoomi-hand-raised-end': '#f472b6',
      '--zoomi-hand-raised-text': '#ffffff',
      '--zoomi-hand-raised-shadow': 'rgba(244,114,182,0.4)',
      '--zoomi-mute-unmuted': '#34d399',
      '--zoomi-mute-unmuted-hover': '#10b981',
      '--zoomi-mute-unmuted-shadow': 'rgba(52,211,153,0.3)',
      '--zoomi-mute-muted': '#f472b6',
      '--zoomi-mute-muted-hover': '#ec4899',
      '--zoomi-mute-muted-shadow': 'rgba(244,114,182,0.3)',
      '--zoomi-minimize-bg': '#fce4ec',
      '--zoomi-minimize-text': '#f472b6',
      '--zoomi-focus-color': '#f472b6',
    },
    emojiColors: ['#fce4ec', '#e0f7fa', '#fff9c4', '#e8f5e9', '#f3e5f5', '#fff3e0'],
  },
};

export const themeIds = Object.keys(themes) as ThemeId[];
